// const presentInFigmaButNotInAntd = ['--------Below were deprecated in v5+', 'PageHeader', 'Comment'];

// const presentInAntdButNotInFigma = [
//   'Spin',
//   'Mentions',
//   '--------Below were added in v5+',
//   'FloatButton',
//   'Flex',
//   'Tour',
//   'Splitter',
//   'ColorPicker',
//   'QRCode',
//   'Watermark',
// ];

const presentInBoth = [
  // 'Button',
  // 'Input',
  // 'AutoComplete',
  // 'Avatar',
  // 'Badge',
  // 'Breadcrumb',
  // 'Calendar',
  // 'Cascader',
  // 'Checkbox',
  // 'Collapse',
  // 'Dropdown',
  // 'Menu',
  // 'Pagination',
  // 'Steps',
  // 'InputNumber',
  // 'Anchor',
  // 'Divider',
  // 'DatePicker',
  // 'Radio',
  // 'Rate',
  // 'Select',
  // 'Slider',
  // 'Switch',
  // 'TimePicker',
  // 'TreeSelect',
  // 'Carousel',
  // 'Empty',
  // 'List',
  // 'Popover',
  // 'Statistic',
  // 'Tag',
  // 'Timeline',
  // 'Tooltip',
  // 'Alert',
  // 'Drawer',
  // 'Modal',
  // 'Popconfirm',
  // 'Progress',
  // 'Result',
  // 'Skeleton',
  'Descriptions',
  'Upload',
  'Card',
  'Form',
  'Transfer',
  'Image',
  'Segmented',
  'Table',
  'Tabs',
  'Tree',
  'Message',
  'Notification',
];
